
package com.proitc.wss.endpoint;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DemoServiceEndpointPortType", targetNamespace = "http://endpoint.wss.proitc.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DemoServiceEndpointPortType {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "http://endpoint.wss.proitc.com/")
    @RequestWrapper(localName = "status", targetNamespace = "http://endpoint.wss.proitc.com/", className = "com.proitc.wss.endpoint.Status")
    @ResponseWrapper(localName = "statusResponse", targetNamespace = "http://endpoint.wss.proitc.com/", className = "com.proitc.wss.endpoint.StatusResponse")
    public String status();

}
