
package com.proitc.wss.endpoint;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DemoServiceEndpoint", targetNamespace = "http://endpoint.wss.proitc.com/", wsdlLocation = "/service-api-definition/DemoServiceEndpoint.wsdl")
public class DemoServiceEndpoint
    extends Service
{

    private final static URL DEMOSERVICEENDPOINT_WSDL_LOCATION;
    private final static WebServiceException DEMOSERVICEENDPOINT_EXCEPTION;
    private final static QName DEMOSERVICEENDPOINT_QNAME = new QName("http://endpoint.wss.proitc.com/", "DemoServiceEndpoint");

    static {
        DEMOSERVICEENDPOINT_WSDL_LOCATION = com.proitc.wss.endpoint.DemoServiceEndpoint.class.getResource("/service-api-definition/DemoServiceEndpoint.wsdl");
        WebServiceException e = null;
        if (DEMOSERVICEENDPOINT_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/service-api-definition/DemoServiceEndpoint.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        DEMOSERVICEENDPOINT_EXCEPTION = e;
    }

    public DemoServiceEndpoint() {
        super(__getWsdlLocation(), DEMOSERVICEENDPOINT_QNAME);
    }

    public DemoServiceEndpoint(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEMOSERVICEENDPOINT_QNAME, features);
    }

    public DemoServiceEndpoint(URL wsdlLocation) {
        super(wsdlLocation, DEMOSERVICEENDPOINT_QNAME);
    }

    public DemoServiceEndpoint(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEMOSERVICEENDPOINT_QNAME, features);
    }

    public DemoServiceEndpoint(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DemoServiceEndpoint(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DemoServiceEndpointPortType
     */
    @WebEndpoint(name = "DemoServiceEndpointPort")
    public DemoServiceEndpointPortType getDemoServiceEndpointPort() {
        return super.getPort(new QName("http://endpoint.wss.proitc.com/", "DemoServiceEndpointPort"), DemoServiceEndpointPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DemoServiceEndpointPortType
     */
    @WebEndpoint(name = "DemoServiceEndpointPort")
    public DemoServiceEndpointPortType getDemoServiceEndpointPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://endpoint.wss.proitc.com/", "DemoServiceEndpointPort"), DemoServiceEndpointPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEMOSERVICEENDPOINT_EXCEPTION!= null) {
            throw DEMOSERVICEENDPOINT_EXCEPTION;
        }
        return DEMOSERVICEENDPOINT_WSDL_LOCATION;
    }

}
